---
# 'service reload' was not always working, needs complete reload
- name: firewalld complete reload
  command: firewall-cmd --complete-reload

- name: firewalld complete restart
  ansible.builtin.service:
    name: firewalld
    state: restarted
